#
# This workflow calls the main distribution pipeline from DuckDB to build, test and (optionally) release the extension
#
name: Main Extension Distribution Pipeline
on:
  push:
    tags: ["*"]
  pull_request:
  release:
    types: [published]
  workflow_dispatch:

permissions:
  contents: write

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    name: Build extension binaries
    uses: duckdb/extension-ci-tools/.github/workflows/_extension_distribution.yml@v1.5-variegata
    with:
      duckdb_version: v1.5.5
      ci_tools_version: v1.5-variegata
      extension_name: duckdb_git
      extra_toolchains: rust;python3
      exclude_archs: "wasm_mvp;wasm_eh;wasm_threads;windows_amd64_mingw"

  release:
    runs-on: ubuntu-latest
    if: >
      startsWith(github.ref, 'refs/tags/') ||
      github.event_name == 'release'
    needs: build
    steps:
      - name: Restore
        uses: actions/download-artifact@v4
        with:
          pattern: duckdb_git-*-extension-*
          path: artifacts

      - name: Run gh-describe
        id: ghd
        uses: proudust/gh-describe@v2
        with:
          repo: ${{ github.repository }}
          commit-ish: ${{ github.sha }}

      - name: Upload release assets
        run: |
          for dir in artifacts/*/; do
            arch=$(basename "$dir" | sed 's/duckdb_git-v[0-9.]*-extension-//')
            gzip -c "$dir"/*.duckdb_extension >"artifacts/duckdb_git.duckdb_extension.${arch}.gz"
          done
          if gh release view "${GITHUB_RELEASE_TAG}" --json tagName >/dev/null 2>&1; then
            gh release upload --clobber "${GITHUB_RELEASE_TAG}" artifacts/*.duckdb_extension.*.gz
          else
            gh release create -d --generate-notes "${GITHUB_RELEASE_TAG}" artifacts/*.duckdb_extension.*.gz
          fi
        env:
          GH_REPO: ${{ github.repository }}
          GITHUB_RELEASE_TAG: ${{ steps.ghd.outputs.tag }}
          GITHUB_TOKEN: ${{ github.token }}
